// import type { Metadata } from 'next'
import './globals.css'
import { AppRouterCacheProvider } from '@mui/material-nextjs/v13-appRouter';
import { ThemeProvider } from '@mui/system';
import theme from './theme';
import { emojiIndexToName } from '@/utils/emoji';


// or `v1X-appRouter` if you are using Next.js v1X

// export const metadata: Metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <head>
        {
          Array.from({ length: 17 }, (_, index) => (
            <link key={index} rel="preload" href={`emojis/${emojiIndexToName[index]}`} as="image" />
          ))
        }
      </head>
      <body>
        <ThemeProvider theme={theme}>
          <AppRouterCacheProvider>{children}</AppRouterCacheProvider>
        </ThemeProvider>
      </body>
    </html>
  )
}
